[package]
name = "shielded-pool"
version = "0.1.0"
edition = "2024"

[dependencies]
midnight-circuits = { git = "https://github.com/jtcoolen/midnight-zk", branch = "fix/fixed-vk-selector-conversion-2" }
midnight-aggregator = { package = "midnight-aggregation", git = "https://github.com/jtcoolen/midnight-zk", branch = "fix/fixed-vk-selector-conversion-2", optional = true }
midnight-curves = { git = "https://github.com/jtcoolen/midnight-zk", branch = "fix/fixed-vk-selector-conversion-2" }
midnight-proofs = { git = "https://github.com/jtcoolen/midnight-zk", branch = "fix/fixed-vk-selector-conversion-2" }
midnight-zk-stdlib = { git = "https://github.com/jtcoolen/midnight-zk", branch = "fix/fixed-vk-selector-conversion-2" }
sha2 = "0.10.9"
rand = "0.8"
rand_chacha = "0.3"
ff = "0.13.1"
group = "0.13.0"
rayon = "1.11.0"
blake2b_simd = "1.0.3"
sha3 = "0.10.8"
thiserror = "2.0.18"

[dev-dependencies]
proptest = "1.9.0"

[features]
default = ["truncated-challenges"]
dev-curves = [
  "midnight-curves/dev-curves",
  "midnight-proofs/dev-curves",
  "midnight-circuits/dev-curves",
]
truncated-challenges = [
  "midnight-proofs/truncated-challenges",
  "midnight-circuits/truncated-challenges",
]
fewer-point-sets = [
  "midnight-proofs/fewer-point-sets",
  "midnight-circuits/fewer-point-sets",
]

# only build aggregator when you explicitly ask for it
aggregation = ["midnight-aggregator"]

[patch.crates-io]
midnight-circuits = { git = "https://github.com/jtcoolen/midnight-zk", branch = "fix/fixed-vk-selector-conversion-2" }
midnight-curves = { git = "https://github.com/jtcoolen/midnight-zk", branch = "fix/fixed-vk-selector-conversion-2" }
midnight-proofs = { git = "https://github.com/jtcoolen/midnight-zk", branch = "fix/fixed-vk-selector-conversion-2" }
midnight-zk-stdlib = { git = "https://github.com/jtcoolen/midnight-zk", branch = "fix/fixed-vk-selector-conversion-2" }

[patch."https://github.com/midnightntwrk/midnight-zk"]
midnight-aggregation = { git = "https://github.com/jtcoolen/midnight-zk", branch = "fix/fixed-vk-selector-conversion-2" }
midnight-circuits = { git = "https://github.com/jtcoolen/midnight-zk", branch = "fix/fixed-vk-selector-conversion-2" }
midnight-curves = { git = "https://github.com/jtcoolen/midnight-zk", branch = "fix/fixed-vk-selector-conversion-2" }
midnight-proofs = { git = "https://github.com/jtcoolen/midnight-zk", branch = "fix/fixed-vk-selector-conversion-2" }
midnight-zk-stdlib = { git = "https://github.com/jtcoolen/midnight-zk", branch = "fix/fixed-vk-selector-conversion-2" }
